/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker is generated by the vite-plugin-pwa and is only used for production
// The workbox window library will register this service worker automatically

// Declare the ServiceWorkerGlobalScope
declare const self: ServiceWorkerGlobalScope;

// Skip waiting and claim clients to ensure an immediate takeover
self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
}); 